// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function UpdateWindowTitle(arg1) {
  return window['go']['main']['App']['UpdateWindowTitle'](arg1);
}
