// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {exchange} from '../models';

export function GetPositions():Promise<Array<exchange.Position>>;
